--- # clusterIp for redis (to connect from same namespace applciations)
apiVersion: v1
kind: Service
metadata:
  name: bb-cache
# you can use this service with hostname bb-cache in the same namespace
spec:
  selector:
    app: bb-cache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
